### ISSUE TITLE
Make refresh token usable only once.

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/ManagementPortal#242] opened 2018-03-22 16:50 UTC
As pointed out by @dennyverbeeck, Right now a refresh token, and thus also a qr code, can be reused many times as long as it's not expired, but it might be more secure to only allow them to be used once.

**Comment by blootsvoets** [comment] 2018-03-28 11:50
Implementing this (in #241) may give a significant flow problems, because as far as I see, it applies not only to the QR code, but also to the refresh tokens retrieved when the access token is renewed. Questions and potential problems:

1. **Scenario**: A client scans the wrong QR code. It is submitted to the server. Now the client that the QR code was intended for, cannot use the QR code either. **Consequence**: Whenever an error is made, a new print-out is needed. Ergo, printing QR codes for a participant is not that useful. 
2. **Scenario**: a client makes a request for a new access token, using a refresh token. The request handling fails before the new refresh token is stored (e.g., network failure, app failure, phone failure). The user now needs a new QR code to use the app again. **Consequence**: data streaming is stopped until manual intervention is taken.
3. **Scenario**: a phone is lost, is recovered from backup, an app is uninstalled or its data is removed. The refresh token is lost. **Consequence**: user cannot use the app again until manual intervention is taken.

To me, these scenarios are quite likely and the consequences are quite severe. They could alleviated by providing participants with a password, in which case all apps also need to be able to be redirected to the MP login screen.

**Comment by dennyverbeeck** [comment] 2018-06-15 11:29
Hmm, these are valid concerns as well. My concern was mostly for the scenario where a QR code is printed out. If refresh token reuse is possible then this print-out becomes effectively the same as a print-out of a username and password (although limited by the expiration time). I'm not sure how often a print is made though. Perhaps the solution here is proper training for the participant onboarding staff, making clear that the QR code allows anyone to log in on behalf of the participant, and that appropriate care should be taken.

I'm fine with leaving the reuse allowed and closing this. What do you think @yatharthranjan @blootsvoets ?

**Comment by dennyverbeeck** [comment] 2018-06-25 15:07
Based on our discussion in the weekly meeting, we will allow refresh tokens to be used multiple times. Closing this issue.

**Closed by dennyverbeeck** 2018-06-25 15:07 UTC
Labels: enhancement
