### ISSUE TITLE
Confirmation on activation link sent?

### ISSUE THREAD

**Issue by baixiac** [RADAR-base/ManagementPortal#612] opened 2021-05-28 11:15 UTC
After the "Send" button is clicked, should the dialog be closed or replaced by a new message like "activation link sent" ? Currently, the user has no feedback on the sending has been successful or not.

![confirm_sending_activation_link](https://user-images.githubusercontent.com/82581439/119975457-c927ac80-bfad-11eb-8501-02460d418f89.png)

**Comment by blootsvoets** [comment] 2021-05-28 12:46
Duplicate of #567.

**Closed by blootsvoets** 2021-05-28 12:46 UTC
