### ISSUE TITLE
Access denied after login

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/ManagementPortal#457] opened 2019-07-02 07:37 UTC
When navigating to a URL without being logged in, you get redirected to a login page. However, after logging in, you are still on the "Access denied" page `/managementportal/#/accessdenied` because the URL doesn't revert to the original URL that was navigated to. Would it be possible to encode the original URL in local storage or as a query parameter so that the user gets returned to the intended page after logging in?

**Comment by nivemaham** [comment] 2020-11-09 10:18
Duplicate of #514

**Closed by nivemaham** 2020-11-09 10:18 UTC
